[generation]
mode = "positive"

[checks.positive_data_acceptance]
expected-statuses = [200, 422]

[checks.negative_data_rejection]
expected-statuses = [400]

[warnings]
# Hide just this one warning, keep the others
display = ["missing_auth", "missing_test_data"]
